[versions]
agp = "8.9.0"
kotlin = "2.0.21"

# Core Android
coreKtx = "1.16.0"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
fragmentKtx = "1.8.5"
constraintlayout = "2.2.1"
swiperefreshlayout = "1.1.0"

# Jetpack Lifecycle
lifecycleProcess = "2.8.6"

# Testing
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"

# Third-party
lottie = "3.4.0"
dexter = "6.2.3"
compressor = "3.0.1"
coroutinesPlayServices = "1.7.3"
appUpdateKtx = "2.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# Third-party
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
dexter = { group = "com.karumi", name = "dexter", version.ref = "dexter" }
compressor = { group = "id.zelory", name = "compressor", version.ref = "compressor" }
coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutinesPlayServices" }
app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "appUpdateKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


